-   id: google-java-format
    name: Reformat Java
    description: Reformat Java source code to comply with Google Java Style.
    entry: ./format-code.sh
    language: script
    files: \.java$ # We don't technically need this, as the script will filter for us, but this will allow the hook to be skipped if no Java is changed.

